package io.github.paulmarcelinbejan.fabrick.enumeration;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.JsonNode;

import lombok.Getter;

@Getter
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum GBS_TRANSACTION_TYPE {

	GBS_ACCOUNT_TRANSACTION_TYPE_0001,
	GBS_ACCOUNT_TRANSACTION_TYPE_0002,
	GBS_ACCOUNT_TRANSACTION_TYPE_0003,
	GBS_ACCOUNT_TRANSACTION_TYPE_0004,
	GBS_ACCOUNT_TRANSACTION_TYPE_0005,
	GBS_ACCOUNT_TRANSACTION_TYPE_0006,
	GBS_ACCOUNT_TRANSACTION_TYPE_0007,
	GBS_ACCOUNT_TRANSACTION_TYPE_0008,
	GBS_ACCOUNT_TRANSACTION_TYPE_0009,
	GBS_ACCOUNT_TRANSACTION_TYPE_0010,
	GBS_ACCOUNT_TRANSACTION_TYPE_0011,
	GBS_ACCOUNT_TRANSACTION_TYPE_0012,
	GBS_ACCOUNT_TRANSACTION_TYPE_0013,
	GBS_ACCOUNT_TRANSACTION_TYPE_0014,
	GBS_ACCOUNT_TRANSACTION_TYPE_0015,
	GBS_ACCOUNT_TRANSACTION_TYPE_0016,
	GBS_ACCOUNT_TRANSACTION_TYPE_0017,
	GBS_ACCOUNT_TRANSACTION_TYPE_0018,
	GBS_ACCOUNT_TRANSACTION_TYPE_0019,
	GBS_ACCOUNT_TRANSACTION_TYPE_0020,
	GBS_ACCOUNT_TRANSACTION_TYPE_0021,
	GBS_ACCOUNT_TRANSACTION_TYPE_0022,
	GBS_ACCOUNT_TRANSACTION_TYPE_0023,
	GBS_ACCOUNT_TRANSACTION_TYPE_0024,
	GBS_ACCOUNT_TRANSACTION_TYPE_0025,
	GBS_ACCOUNT_TRANSACTION_TYPE_0026,
	GBS_ACCOUNT_TRANSACTION_TYPE_0027,
	GBS_ACCOUNT_TRANSACTION_TYPE_0028,
	GBS_ACCOUNT_TRANSACTION_TYPE_0029,
	GBS_ACCOUNT_TRANSACTION_TYPE_0030,
	GBS_ACCOUNT_TRANSACTION_TYPE_0031,
	GBS_ACCOUNT_TRANSACTION_TYPE_0032,
	GBS_ACCOUNT_TRANSACTION_TYPE_0033,
	GBS_ACCOUNT_TRANSACTION_TYPE_0034,
	GBS_ACCOUNT_TRANSACTION_TYPE_0035,
	GBS_ACCOUNT_TRANSACTION_TYPE_0036,
	GBS_ACCOUNT_TRANSACTION_TYPE_0037,
	GBS_ACCOUNT_TRANSACTION_TYPE_0038,
	GBS_ACCOUNT_TRANSACTION_TYPE_0039,
	GBS_ACCOUNT_TRANSACTION_TYPE_0040,
	GBS_ACCOUNT_TRANSACTION_TYPE_0041,
	GBS_ACCOUNT_TRANSACTION_TYPE_0042,
	GBS_ACCOUNT_TRANSACTION_TYPE_0043,
	GBS_ACCOUNT_TRANSACTION_TYPE_0044,
	GBS_ACCOUNT_TRANSACTION_TYPE_0045,
	GBS_ACCOUNT_TRANSACTION_TYPE_0046,
	GBS_ACCOUNT_TRANSACTION_TYPE_0047,
	GBS_ACCOUNT_TRANSACTION_TYPE_0048,
	GBS_ACCOUNT_TRANSACTION_TYPE_0049,
	GBS_ACCOUNT_TRANSACTION_TYPE_0050;

	private String enumeration;
	private String value;

	GBS_TRANSACTION_TYPE() {
		enumeration = GBS_TRANSACTION_TYPE.class.getSimpleName();
		value = name();
	}
	
	@JsonCreator
    public static GBS_TRANSACTION_TYPE fronJsonNode(JsonNode node) {
        return GBS_TRANSACTION_TYPE.valueOf(node.get("value").asText());
    }

}
